import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,readdir} from 'node:fs/promises';
import {text,normalize,escapeHTML,searchItems,expandedQuery,queryIntent,textRisk,safetyGate,exerciseAvailable,recommend,toCSV,safeURL,validDate,validateLog,bmi,weightSummary,sessionLoad,readStorage,writeStorage,coverageAudit} from '../src/core.js';
const json=async p=>JSON.parse(await readFile(new URL('../src/data/'+p,import.meta.url),'utf8'));
const plans=await json('plans.json'),exercises=await json('exercises.json');
const equipment=await Promise.all((await readdir(new URL('../src/data/equipment',import.meta.url))).map(x=>json('equipment/'+x)));
const healthy={age:30,urgent:'no',health:'healthy',goal:'hypertrophy',days:2,minutes:50,place:'home',level:'beginner',equipment:['dumbbell']};

test('Simplified Chinese and English text selection',()=>{assert.equal(text({en:'hello','zh-CN':'你好'},'en'),'hello');assert.equal(text({en:'hello','zh-CN':'你好'},'zh-CN'),'你好');});
test('Fallback is deterministic and does not fabricate a translation',()=>{assert.equal(text({en:'hello','zh-CN':'你好'},'ar'),'hello');assert.equal(text({en:'hello','zh-CN':'你好'},'zh-TW'),'你好');assert.equal(text(null),'');});
test('HTML escaping blocks element and attribute injection',()=>assert.equal(escapeHTML('<img x="\'">&'),'&lt;img x=&quot;&#39;&quot;&gt;&amp;'));
test('Accent normalization',()=>assert.equal(normalize(' HAltÈRES '),'halteres'));
for(const query of ['哑铃','啞鈴','mancuernas','Hanteln','ダンベル','덤벨','гантели','دمبل','डम्बल'])test(`Multilingual equipment search: ${query}`,()=>assert(searchItems(equipment,query).some(e=>e.id==='dumbbell')));
test('Plain string source titles can be searched',()=>assert.equal(searchItems([{id:'s',title:'Protein supplementation study'}],'protein')[0].id,'s'));
test('Chinese common alias resolves seated chest press',()=>assert(searchItems(equipment,'坐姿推胸').some(x=>x.id==='chest-press')));
test('Blank search returns bounded results',()=>assert.equal(searchItems(equipment,'',4).length,4));
test('Unknown search returns no fabricated match',()=>assert.equal(searchItems(equipment,'xxzzqv9999').length,0));
test('Natural query parses goal, days and minutes',()=>assert.deepEqual(queryIntent('减脂 3天 60分钟'),{goal:'fat-loss',days:3,minutes:60}));
test('English natural query',()=>assert.deepEqual(queryIntent('fat loss 3 days 30 min'),{goal:'fat-loss',days:3,minutes:30}));
test('Chinese numeral weekly frequency',()=>assert.equal(queryIntent('增肌 每周三天').days,3));
for(const q of ['胸痛','chest pain','douleur thoracique','dolor de pecho','ألم الصدر','brustschmerz','胸の痛み','가슴 통증','боль в груди','सीने में दर्द'])test(`Urgent text trigger: ${q}`,()=>assert.equal(textRisk(q),'urgent'));
test('Negated emergency terms do not silently clear safety',()=>assert.equal(textRisk('I have no chest pain'),'urgent'));
test('Pain inside an unrelated word does not block',()=>assert.equal(textRisk('painting equipment'),'none'));
for(const q of ['膝盖疼','pregnant','diabetes','腰痛','postpartum','knee pain','受伤'])test(`Assessment trigger: ${q}`,()=>assert.equal(textRisk(q),'review'));
test('Missing profile never clears',()=>assert.equal(safetyGate({}).status,'incomplete'));
test('Blank age never becomes an adult',()=>assert.equal(safetyGate({...healthy,age:''}).status,'incomplete'));
test('Healthy adult can match a template, not a diagnosis',()=>assert.equal(safetyGate(healthy).status,'eligible'));
for(const [age,status] of [[17,'review'],[18,'eligible'],[64,'eligible'],[65,'review'],[121,'incomplete'],[-1,'incomplete']])test(`Age boundary ${age}`,()=>assert.equal(safetyGate({...healthy,age}).status,status));
for(const health of ['pain','chronic','pregnancy','eating','disability'])test(`Health restriction ${health} blocks recommendations`,()=>assert.equal(recommend(plans,exercises,{...healthy,health}).results.length,0));
test('Unknown safety answer never clears',()=>assert.equal(safetyGate({...healthy,urgent:'unknown'}).status,'incomplete'));
test('Emergency response takes priority over missing age',()=>assert.equal(safetyGate({urgent:'yes'}).status,'urgent'));
test('Free text can override healthy selection',()=>assert.equal(recommend(plans,exercises,healthy,'胸痛 增肌').gate.status,'urgent'));
test('Equipment options use AND within each option, OR between options',()=>{const x={equipmentOptions:[['a','b'],['c']]};assert.equal(exerciseAvailable(x,['a']),false);assert.equal(exerciseAvailable(x,['a','b']),true);assert.equal(exerciseAvailable(x,['c']),true);});
test('No equipment requirement is explicit',()=>assert(exerciseAvailable({equipmentOptions:[[]]},[])));
test('Dumbbell plan matches with actual dumbbells',()=>assert(recommend(plans,exercises,healthy).results.some(r=>r.plan.id==='muscle-db-2')));
test('Adjustable dumbbells are a valid alternative',()=>assert(recommend(plans,exercises,{...healthy,equipment:['adjustable-dumbbell']}).results.some(r=>r.plan.id==='muscle-db-2')));
test('No equipment is not assumed to mean a full gym',()=>assert.equal(recommend(plans,exercises,{...healthy,equipment:[],place:'gym'}).results.length,0));
test('Mini-band cannot silently substitute for long loop',()=>assert.equal(recommend(plans,exercises,{...healthy,equipment:['mini-band']}).results.length,0));
test('Available time is a hard constraint',()=>assert.equal(recommend(plans,exercises,{...healthy,minutes:20}).results.length,0));
test('Free-text time can tighten but not relax declared time',()=>{assert.equal(recommend(plans,exercises,healthy,'20 min').results.length,0);assert(recommend(plans,exercises,healthy,'90 min').results.every(r=>r.plan.minutes<=50));});
test('Beginner does not get intermediate templates',()=>assert(recommend(plans,exercises,{...healthy,days:4,minutes:90}).results.every(r=>r.plan.level==='beginner')));
test('All matched plans satisfy all hard constraints',()=>{const r=recommend(plans,exercises,{...healthy,days:3,minutes:60});for(const x of r.results){assert(x.plan.days<=3);assert(x.plan.minutes<=60);assert(x.plan.settings.includes('home'));assert.equal(x.plan.goal,'hypertrophy');}});
test('Missing-equipment exclusions explain unmet exercises',()=>{const r=recommend(plans,exercises,{...healthy,equipment:[]});assert(r.excluded.some(x=>x.reasons.includes('equipment')&&x.missing.length));});
test('Fat-loss no-gear starter is explicitly partial',()=>{const r=recommend(plans,exercises,{...healthy,goal:'fat-loss',minutes:30,equipment:[]});assert.equal(r.results.length,1);assert(r.results[0].plan.partial);});
test('No malformed time returns a recommendation',()=>assert.equal(recommend(plans,exercises,{...healthy,minutes:'abc'}).results.length,0));
test('CSV exports quotes and formula-injection protection',()=>{const csv=toCSV([{v:'=HYPERLINK("bad")'},{v:'a,b'}],[{label:'v',value:'v'}]);assert(csv.includes("'="));assert(csv.includes('"a,b"'));assert(csv.startsWith('\uFEFF'));});
for(const url of ['javascript:alert(1)','http://example.org','data:text/html,x','not a url'])test(`Unsafe external URL: ${url}`,()=>assert.equal(safeURL(url),'#'));
test('HTTPS source URL retained',()=>assert.equal(safeURL('https://example.org'),'https://example.org/'));
for(const date of ['2026-02-30','2026-2-01','invalid','2025-02-29'])test(`Invalid calendar date: ${date}`,()=>assert.equal(validDate(date),false));
test('Leap day valid',()=>assert(validDate('2024-02-29')));
test('BMI math in metric units',()=>assert(Math.abs(bmi(70,175)-22.857142857)<1e-7));
for(const pair of [[70,0],[70,1.75],[-2,175],[Infinity,175]])test(`BMI rejects incorrect units / invalid value ${pair}`,()=>assert.throws(()=>bmi(...pair),RangeError));
test('Optional values remain null, not zero',()=>{const x=validateLog({date:'2026-09-29',weight:70});assert(x.valid);assert.equal(x.record.waist,null);});
test('Future records rejected',()=>assert.equal(validateLog({date:'2026-09-30',weight:70},'2026-09-29').valid,false));
test('Null and malformed storage rows rejected safely',()=>{assert.equal(validateLog(null).valid,false);assert.equal(validateLog([]).valid,false);});
test('Out of range measurements rejected',()=>assert.equal(validateLog({date:'2026-09-29',weight:-2}).valid,false));
test('Fractional sets rejected',()=>assert.equal(validateLog({date:'2026-09-29',exercise:'squat',sets:2.2}).valid,false));
test('Training parameters need a task ID',()=>assert.equal(validateLog({date:'2026-09-29',reps:10}).valid,false));
test('Zero RIR and zero external load retained',()=>{const x=validateLog({date:'2026-09-29',exercise:'squat',load:0,rir:0});assert(x.valid);assert.equal(x.record.rir,0);});
test('Empty record is invalid',()=>assert.equal(validateLog({date:'2026-09-29'}).valid,false));
test('Seven-day average uses calendar dates, not last seven entries',()=>{const x=weightSummary([{date:'2026-09-01',weight:100},{date:'2026-09-25',weight:70},{date:'2026-09-29',weight:72}],'2026-09-29');assert.equal(x.average,71);assert.equal(x.count,2);assert.equal(x.delta,null);});
test('Same-day measurements are averaged before weekly mean',()=>{const x=weightSummary([{date:'2026-09-28',weight:70},{date:'2026-09-28',weight:72},{date:'2026-09-29',weight:73}],'2026-09-29');assert.equal(x.average,72);assert.equal(x.count,2);});
test('Future and invalid weights do not enter summaries',()=>{const x=weightSummary([{date:'2026-09-30',weight:70},{date:'bad',weight:72},{date:'2026-09-29',weight:Infinity}],'2026-09-29');assert.equal(x.average,null);});
test('Stale log is not presented as this week',()=>assert.equal(weightSummary([{date:'2020-01-01',weight:70}],'2026-09-29').count,0));
test('Two-window difference needs three days per window',()=>{const records=[20,21,22,27,28,29].map(d=>({date:`2026-09-${d}`,weight:d<23?71:70}));assert.equal(weightSummary(records,'2026-09-29').delta,-1);});
test('Session proxy retains zero effort',()=>assert.equal(sessionLoad(30,0),0));
test('Session proxy does not fill missing data',()=>assert.equal(sessionLoad('',5),null));
test('Session proxy rejects impossible values',()=>assert.throws(()=>sessionLoad(30,11),RangeError));
test('Blocked local storage is handled',()=>{const bad={getItem(){throw Error('blocked')},setItem(){throw Error('blocked')}};assert.deepEqual(readStorage(bad,'x',[]),[]);assert.equal(writeStorage(bad,'x',{}),false);});
test('Corrupt local storage is handled',()=>assert.deepEqual(readStorage({getItem:()=>'{bad'},'x',[]),[]));
test('Coverage has no invented denominator',()=>assert.deepEqual(coverageAudit([],['dumbbell']),{status:'not-measured',covered:0,total:0,ratio:null}));
test('Unknown equipment stays in coverage denominator',()=>{const r=coverageAudit([{equipmentId:'dumbbell',count:3},{equipmentId:'unmapped',count:1}],['dumbbell']);assert.equal(r.ratio,.75);assert.equal(r.status,'sample-only');});
test('Invalid coverage counts rejected',()=>assert.throws(()=>coverageAudit([{equipmentId:'x',count:-1}],['x']),RangeError));
