import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,readdir} from 'node:fs/promises';
const json=async p=>JSON.parse(await readFile(new URL('../src/data/'+p,import.meta.url),'utf8'));
const names=['categories','patterns','knowledge','exercises','plans','methods','populations','sources','locales','meta'];
const D=Object.fromEntries(await Promise.all(names.map(async n=>[n,await json(n+'.json')])));
D.equipment=await Promise.all((await readdir(new URL('../src/data/equipment',import.meta.url))).map(x=>json('equipment/'+x)));
const ids=n=>new Set(D[n].map(x=>x.id));
for(const name of ['equipment','categories','knowledge','exercises','plans','methods','populations','sources'])test(`${name}: unique IDs`,()=>assert.equal(ids(name).size,D[name].length));
test('Catalog has 12 primary families and retains the release inventory',()=>{assert.equal(D.categories.length,12);assert(D.equipment.length>=136);});
test('Catalog record filenames match canonical IDs',async()=>{const files=await readdir(new URL('../src/data/equipment',import.meta.url));for(const file of files)assert.equal(file,(await json('equipment/'+file)).id+'.json');});
test('Complete Chinese and English expert core',()=>{for(const group of ['equipment','categories','exercises','plans','methods','populations'])for(const x of D[group]){assert(x.name['zh-CN']?.trim());assert(x.name.en?.trim());}for(const x of D.knowledge){for(const f of ['title','summary','action','scope']){assert(x[f]['zh-CN']);assert(x[f].en);}}});
test('12 navigation packs with exact key parity',()=>{assert.equal(Object.keys(D.locales).length,12);const keys=Object.keys(D.locales.en).sort();for(const l of Object.values(D.locales)){assert.deepEqual(Object.keys(l).sort(),keys);assert(Object.values(l).every(s=>typeof s==='string'&&s.length));}});
test('Machine-readable localization status does not claim complete translations',()=>assert.deepEqual(D.meta.contentLocales,['zh-CN','en']));
test('No fake measured 95% coverage',()=>{assert.equal(D.meta.measuredEquipmentCoverage,null);assert.equal(D.meta.coverageTarget,.95);});
test('No unearned expert approval',()=>{assert.equal(D.meta.professionalReview,'pending');for(const s of D.sources)assert.match(s.reviewStatus,/pending/);});
test('Source identity de-duplicates DOI or canonical document, not host name',()=>{assert.equal(new Set(D.sources.map(s=>s.documentKey)).size,D.sources.length);for(const s of D.sources){assert(s.url.startsWith('https://'));assert.equal(s.checked,'2026-09-29');assert(s.access);assert(s.scope);}});
test('Every knowledge card has at least two different registered documents',()=>{for(const k of D.knowledge){assert(new Set(k.sources).size>=2,k.id);const docs=k.sources.map(id=>D.sources.find(s=>s.id===id)?.documentKey);assert(docs.every(Boolean),k.id);assert(new Set(docs).size>=2,k.id);}});
test('Every equipment reference is valid and scope disclosed',()=>{for(const e of D.equipment){assert(ids('categories').has(e.category));assert(e.evidenceScope.en);assert(e.use.en);assert(e.caution.en);assert(e.patterns.every(p=>D.patterns[p]));assert(e.alternatives.every(a=>ids('equipment').has(a)&&a!==e.id));assert(e.sources.every(s=>ids('sources').has(s)));}});
test('All families populated',()=>{for(const c of D.categories)assert(D.equipment.some(e=>e.category===c.id));});
test('No synthetic efficacy scores or made-up calories/min',()=>{for(const e of D.equipment){assert(!('efficacyScore'in e));assert(!('caloriesPerMinute'in e));assert(!('injuryRate'in e));}});
test('Equipment facet enums valid',()=>{for(const e of D.equipment){assert(['low','moderate','high'].includes(e.learning));assert(['pocket','small','medium','large'].includes(e.footprint));assert(['self','guided','cyclic','support','measurement'].includes(e.path));assert(e.settings.every(x=>['home','gym','outdoor'].includes(x)));}});
test('Exercise equipment options are AND/OR lists of existing equipment',()=>{for(const x of D.exercises){assert(x.equipmentOptions.length);for(const option of x.equipmentOptions)for(const id of option)assert(ids('equipment').has(id),id);assert(x.sources.every(id=>ids('sources').has(id)));}});
test('Plan day counts equal actual scheduled sessions',()=>{for(const p of D.plans)assert.equal(p.days,p.sessions.length,p.id);});
test('All plan exercises including cardio exist',()=>{for(const p of D.plans)for(const s of p.sessions){for(const r of s.exercises){assert(ids('exercises').has(r.exercise));assert(r.sets>=1);assert(r.restSeconds>=0);assert(r.reps&&r.rir);}if(s.cardioMinutes){assert(ids('exercises').has(s.cardioExercise));assert(s.cardioMinutes<p.minutes);}else assert.equal(s.cardioExercise,null);}});
test('Plans have actionable warm-up, progression, stops, sources and limitations',()=>{for(const p of D.plans){for(const k of ['warmup','progression','stop','evidenceScope','notes'])assert(p[k].en&&p[k]['zh-CN']);assert(p.sources.length>=2);assert(p.sources.every(id=>ids('sources').has(id)));}});
test('Full-body dumbbell template includes squat, hinge, horizontal pull and push each session',()=>{for(const s of D.plans.find(p=>p.id==='muscle-db-2').sessions){const patterns=s.exercises.map(r=>D.exercises.find(x=>x.id===r.exercise).pattern);for(const pattern of ['squat','hinge','pull','push'])assert(patterns.includes(pattern),pattern);}});
test('Public partial programs disclose their gaps',()=>{for(const p of D.plans.filter(p=>p.partial))assert.match(p.notes.en,/lacks|lacks|no loaded|Limitation/i);});
test('Population links point to actual knowledge',()=>{for(const p of D.populations)assert(p.knowledge.every(id=>ids('knowledge').has(id)));});
test('Method sources exist and do not claim tested superiority',()=>{for(const m of D.methods){assert(m.sources.every(id=>ids('sources').has(id)));assert.match(m.reviewStatus,/not superiority/);}});
test('SVG assets are original local schematics with no scripts or remote links',async()=>{for(const file of await readdir(new URL('../src/assets',import.meta.url))){const s=await readFile(new URL('../src/assets/'+file,import.meta.url),'utf8');assert(s.includes('<title'));assert(!/<script|foreignObject|\bon\w+=|(?:href|src)\s*=/i.test(s),file);}});
test('All equipment images exist',async()=>{const images=new Set(await readdir(new URL('../src/assets',import.meta.url)));for(const e of D.equipment)assert(images.has(e.image),e.id);});
test('Date of review is explicit, not a perpetual claim to latest',()=>assert.equal(D.meta.reviewedAt,'2026-09-29'));

test("Knowledge source-role audit covers every cited document",()=>{for(const k of D.knowledge){assert(k.auditLabel.en);assert.deepEqual(k.sourceRoles.map(r=>r.source),k.sources);for(const r of k.sourceRoles)assert(r.role.en&&r.role["zh-CN"]);}});
